export const titleToDBKey: Record<string, string> = {
  "Market Cap": "market_cap",
  Price: "price",
  "Volume (24h)": "off_chain_volume",
  "DEX Volume (24h)": "volume",
  "Circulating Supply": "circulating_supply",
  "Change (24h)": "price_change_24h",
  "24h (%)": "price_change_24h",
  "1h %": "price_change_1h",
  "24h %": "price_change_24h",
  "7d %": "price_change_7d",
  "1m %": "price_change_1m",
  "3m %": "price_change_3m",
  "6m %": "price_change_6m",
  "1y %": "price_change_1y",
  "Change (7d)": "price_change_7d",
  "24h Volume": "volume",
  "7d Volume": "volume_7d",
  "1m Volume": "volume_1m",
  Liquidity: "liquidity",
  "Price ETH": "price",
  "Price BTC": "price",
  Rank: "rank",
  Balance: "balance",
  "Full Dil. Valuation": "market_cap_diluted",
  "Circ. Supply": "circulating_supply",
};
