import { WatchlistProvider } from "features/user/watchlist/context-manager";
import type { Metadata } from "next";
import { cookies, headers } from "next/headers";
import React from "react";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import { GeneralContext } from "../contexts";
import { PortfolioV2Provider } from "../features/user/portfolio/context-manager";
import { UserBalanceProvider } from "../layouts/header/context-manager/balance";
import Layout from "../layouts/layout";
import { ThemeProvider } from "../lib/next-theme";
import "../styles/global.css";

export const metadata: Metadata = {
  title: "Mobula | The Web3-native crypto data aggregator",
  description: "Generated by create next app",
  robots: "index, follow",
  viewport: "width=device-width, initial-scale=1",
  keywords:
    "Mobula, Mobula crypto, Mobula Crypto Data Aggregator, crypto, mobula, swap",
};

async function RootLayout({
  children,
  params,
}: {
  children: React.ReactNode;
  params: any;
}) {
  const cookieStore = cookies();
  const userCookie = cookieStore.get("user-balance")?.value;
  const tradeFilterCookie = cookieStore.get("trade-filter")?.value;
  const userAgent: string = headers().get("user-agent") || "";
  const isMobile = /mobile/i.test(userAgent) && !/tablet/i.test(userAgent);
  // isWalletExplorer={pageProps.isWalletExplorer}
  // isPortfolioExplorer={pageProps.isPortfolioExplorer}
  // const portfolio = cookies?.portfolio ? JSON.parse(cookies?.portfolio) : null;

  return (
    <html lang="en">
      <body>
        <ToastContainer
          toastClassName="bg-light-bg-terciary dark:bg-dark-bg-terciary text-light-font-100 dark:text-dark-font-100
           rounded-xl shadow-md border border-light-border-primary dark:border-dark-border-primary pt-3 px-3"
          bodyClassName="bg-light-bg-terciary dark:bg-dark-bg-terciary text-light-font-100 dark:text-dark-font-100"
        />
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <UserBalanceProvider balanceCookies={userCookie}>
            <GeneralContext>
              <WatchlistProvider watchlist={params.watchlist}>
                <PortfolioV2Provider isMobile={isMobile}>
                  <Layout>{children}</Layout>
                </PortfolioV2Provider>
              </WatchlistProvider>
            </GeneralContext>
          </UserBalanceProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}

export default RootLayout;
