import { WatchlistProvider } from "features/user/watchlist/context-manager";
import type { Metadata } from "next";
import { cookies, headers } from "next/headers";
import React from "react";
import { GeneralContext } from "../contexts";
import { PortfolioV2Provider } from "../features/user/portfolio/context-manager";
import Layout from "../layouts/layout";
import { ThemeProvider } from "../lib/next-theme";
import "../styles/global.css";

export const metadata: Metadata = {
  title: "Mobula | Home",
  description: "Generated by create next app",
};

async function RootLayout({
  children,
  params,
}: {
  children: React.ReactNode;
  params: any;
}) {
  const cookieStore = cookies();
  const userCookie = cookieStore.get("user-balance")?.value;
  const tradeFilterCookie = cookieStore.get("trade-filter")?.value;
  const userAgent: string = headers().get("user-agent") || "";
  const isMobile = /mobile/i.test(userAgent) && !/tablet/i.test(userAgent);
  console.log("TA GRAND MERE LA PUTE", params);
  // isWalletExplorer={pageProps.isWalletExplorer}
  // isPortfolioExplorer={pageProps.isPortfolioExplorer}
  // const portfolio = cookies?.portfolio ? JSON.parse(cookies?.portfolio) : null;
  return (
    <html lang="en">
      <body>
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <GeneralContext>
            <WatchlistProvider watchlist={params.watchlist}>
              <PortfolioV2Provider isMobile={isMobile}>
                <Layout>{children}</Layout>
              </PortfolioV2Provider>
            </WatchlistProvider>
          </GeneralContext>
        </ThemeProvider>
      </body>
    </html>
  );
}

export default RootLayout;
