export const ENABLED_FEATURES = [
  "save_chart_properties_to_local_storage",
  "use_localstorage_for_settings",
  // "hide_last_na_study_output",
  // "dont_show_boolean_study_arguments",
];

export const DISABLED_FEATURES = [
  // "header_widget",
  // "header_symbol_search",
  // "header_saveload",
  // "header_symbol_search_hot_key",
  // "header_interval_dropdown",
  // "header_undo_redo",
  // "header_screenshot",
  // "header_settings",
  // "header_fullscreen_button",
  // "header_indicators",
  // "header_interval_dialog_button",
  "header_compare",
  // "header_chart_type",
  // "header_interval_dialog_button",
  //    "header_saveload",defzfefefe
  "header_symbol_search",
  "symbol_info",
  "volume_force_overlay",
  "show_interval_dialog_on_key_press",
  "symbol_search_hot_key",
  "symbol_info",
  "display_market_status",
  "volume_force_overlay",
  "compare_symbol",
  // "border_around_the_chart",
  // "remove_library_container_border",
  "show_interval_dialog_on_key_press",
];
